SELECT 
    CATEGORY,
    ROUND(AVG(PRICE_MINUS_DISCOUNT), 4) AS average_price
FROM (
    SELECT 
        P.CATEGORY,
        P.ID AS PRODUCT_ID,
        (P.PRICE - P.DISCOUNT) AS PRICE_MINUS_DISCOUNT
    FROM 
        PRODUCT AS P
    JOIN (
        SELECT DISTINCT 
            PRODUCT_ID
        FROM 
            PURCHASE
    ) AS PURCHASED_PRODUCTS
    ON 
        P.ID = PURCHASED_PRODUCTS.PRODUCT_ID
) AS DISTINCT_PURCHASED_PRODUCTS
GROUP BY 
    CATEGORY;